### ISSUE TITLE
リクエストボディの定義

### ISSUE THREAD

**Issue by Be3751** [hoka-isdl/MERS#1]
### 概要
各エンドポイントにおけるリクエストボディを定義する。
リクエストボディのフォーマットは、JSONとする。  

具体的なタスク内容としては、JSONスキーマをyamlファイルで定義する。
[ドキュメント内にあるAPI設計](https://www.notion.so/ad45ab7204404a338db41ee1d315d0fd?pvs=4#5253a3bd1cd34f4488c6e2c0298780a4)にある空のコードブロックに記述してください。

### 参考
JSONスキーマについて
https://qiita.com/sagaraya/items/115c15c0df3e84ecbc7f

**Comment by hoka-isdl** [comment]
リクエストボディを定義しました．
レビューお願いします．
被験者情報を作成するリクエストボディはDEAPデータセットを参考にしました．
複数画像を取得するリクエストボディがあっているか少し不安です．

**Comment by Be3751** [comment]
概ね良さそう！ありがとう。
以下、修正点です。
- `POST images/`ではなく`GET /images`。動画も同様に。
- `Consent to distribute physiological recordings`と`Consent to publish audio-visual recordings`は可否を表すっぽいので、boolかな。
- 感情評価値には、familityって項目もint型であるみたいなので、とりあえず足しておこう。
- 各種idは、負の値は入れたくないので、uint型が良いかな。

**Comment by hoka-isdl** [comment]
レビューありがとうございます．
添削箇所に関して，修正しました．
ご確認よろしくお願いします．

**Comment by Be3751** [comment]
ありがとう！もう少し詰めたい部分があって、OpenAPIの説明も兼ねてそこは今度一緒にやりましょう。
