### ISSUE TITLE
アプリケーションの起動/停止方法をREADMEに記載

### ISSUE THREAD

**Issue by hoka-isdl** [hoka-isdl/MERS#44]
表題の通りで、起動/停止の際に実行するコマンドをREADME.mdに追記する。

**Comment by hoka-isdl** [comment]
READMEに使用技術、システム構成、コンテナの起動方法を追記しました。
開発方法に関しては`git clone`から手順を書いた方が良いでしょうか。
初回は`node_module`がないため、`npm install`を実行するなどの手順を書いた方が良いか迷いました。

コミット
- [563bcb0](https://github.com/hoka-isdl/MERS/commit/563bcb0705e2a450dbeaad8162b6282e3797cf7f)

**Comment by Be3751** [comment]
@hoka-isdl 
ごめん、質問に気づけてなかったわ...。
`git clone` とかのgit周りは不要で、 `npm install`は環境構築のセクションに追記した方が良さそうやね。
やっときます。
