### ISSUE TITLE
データベースにchannelテーブルを作成する

### ISSUE THREAD

**Issue by hoka-isdl** [hoka-isdl/MERS#48]
## 概要
trialsテーブルとsignalsテーブルが現状1対1だが、channelテーブルを作成し、外部キーを持たせて1対多の関係を作る。

それに伴って、signalsテーブルに保存するコードを書き換える。

**Comment by Be3751** [comment]
チャンネル毎にデータを保存する動機がまだ見出せないので、一旦closeする。
MaP1058クライアントが導入できたら、技術的にはチャンネル毎のデータ保存が可能になるので、それ以降に動機があれば改めて考える。
