### ISSUE TITLE
Dockerを用いたコンテナアプリケーションの構築

### ISSUE THREAD

**Issue by hoka-isdl** [hoka-isdl/MERS#5]
### 概要
Dockerによるコンテナ環境上に、フロントエンドのアプリケーションを立ち上げる。
バックエンドのコンテナ環境も後で追加する予定なので、現状コンテナが1つだけではあるけど、ルートディレクトリにdocker-compose.yamlを作成してコンテナ環境を構築する。

### フロントエンド
TypeScriptで書けるReactプロジェクトを立ち上げる。
frontendディレクトリをrootディレクトリ下に作成し、frontendディレクトリをReactプロジェクトと対応させる。

**Comment by Be3751** [comment]
以下のPRで本Issueを解決
- #7
